#!/usr/bin/env bash
set -x
if [ ! -e .git ]; then
  [ x$1 == x ] && echo '请输入git仓库名' && exit 1
  git clone root@media.hui8.com.cn:/jo/$1 && cd $1 || exit 1
fi
[ ! -e .git ] && echo '不是一个有效的仓库' && exit 1
cdir=`pwd`
gdir=$cdir

###########
file=$gdir/.git/hooks/pre-push

cat > $file << EOF
#!/bin/bash

while read local_ref local_sha remote_ref remote_sha
do
    cd $cdir
    npm run pre-push || exit 1
done

exit 0
EOF

chmod a+x $file

###########
repo=`basename $cdir`

git remote add test root@media-test.hui8.com.cn:/jo/$repo > /dev/null 2>&1
git fetch test product && git checkout -b product test/product > /dev/null 2>&1
git fetch test test && git checkout -b test test/test > /dev/null 2>&1
git branch -u origin/master master
git branch -u test/test test
git branch -u test/product product
git checkout master
